### ISSUE TITLE
Question: how insert a note? Error: Buffer read only

### ISSUE THREAD

**Issue by poulpoulsen** [deusmax/gnus-notes#5]
Hello,
i try to insert a note with the hydra from your package, but unfortunately gnus complains Buffer read only.
Could you please explain the steps to insert a note?

Thanks
Poul

**Comment by deusmax** [comment]
Hi Poul,
The action [F6] "insert quick-note" will insert a quick note, as a org-list item, to a buffer you are visiting and for which you have write permissions.
So the sequence should be:
1. You are visiting/editing a file, such as mynewidea.org
2. Call gnus-note, using <C-c m> (gnus-notes-helm).
3. Select the item you want
4. Press the action F6 "insert-quick-note" to insert a brief note into your mynewidea.org file and close the helm instance.

Calling  gnus-notes-helm from a gnus buffer will not let the insert to take place. So, that is the expected behavior.
Did I understand your question correctly ?

I guess the action could be deactivated, when not applicable.

**Comment by poulpoulsen** [comment]
Wondeful!
I understand, it works.
Thanks for this handy package.
I will investigate further and come back with upcoming questions, if there will be any...
Regards
Poul

**Comment by Thaodan** [comment]
If it can't find your notes file this error will happen too.

I had that error when I didn't use expand-file-name on ~/file.org.

**Comment by deusmax** [comment]
Action "insert quick-note", now [F8], inserts a note at point of current buffer. It doesnt have to "find" the buffer/file.
